---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
  namespace: downloads
spec:
  capacity:
    storage: ${VOLSYNC_CAPACITY}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - hard
    - rw
  nfs:
    path: /mnt/highwrite/k3s-staging/config/prowlarr
    server: nietzsche.impetuo.us

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
  namespace: downloads
spec:
  volumeName: prowlarr-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY}
