---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nietzsche-k3s-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.1.50.15
  share: /mnt/highwrite/k3s-staging/volumes
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
