---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-secret
    template:
      engineVersion: v2
      data:
        # For Sonarr App
        SONARR__API_KEY: "{{ .SONARR_API_KEY }}"
        SONARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        SONARR__POSTGRES_PORT: "5432"
        SONARR__POSTGRES_USER: &dbUser "{{ .SONARR__POSTGRES_USER }}"
        SONARR__POSTGRES_PASSWORD: &dbPass "{{ .SONARR__POSTGRES_PASSWORD }}"
        SONARR__POSTGRES_MAIN_DB: sonarr_main
        SONARR__POSTGRES_LOG_DB: sonarr_log
        # To initiate Postgres DBs
        INIT_POSTGRES_DBNAME: sonarr_main sonarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: cloudnative-pg
