---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
  namespace: downloads
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nietzsche-nfs-config
  mountOptions:
    - nfsvers=4.1
    - hard
    - rw
  nfs:
    server: 10.1.50.15
    path: /mnt/highwrite/k3s-staging/config/radarr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: downloads
spec:
  storageClassName: nietzsche-nfs-config
  volumeName: radarr-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
