---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        # For RADARR App
        RADARR__API_KEY: "{{ .RADARR_API_KEY }}"
        RADARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        RADARR__POSTGRES_PORT: "5432"
        RADARR__POSTGRES_USER: &dbUser "{{ .RADARR__POSTGRES_USER }}"
        RADARR__POSTGRES_PASSWORD: &dbPass "{{ .RADARR__POSTGRES_PASSWORD }}"
        RADARR__POSTGRES_MAIN_DB: radarr_main
        RADARR__POSTGRES_LOG_DB: radarr_log
        # To initiate Postgres DBs
        INIT_POSTGRES_DBNAME: radarr_main radarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: cloudnative-pg
