apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:XdXdSqiq5odVT53fEfYi5kMo,iv:Ob+EvWImM9y65T45gJdG22GmeYeDtJgtHoOB3G0NkKM=,tag:x1ogxMwFTmkBnXZOvShK0A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5B4MADpEMRrg9VYUFmazBTMDaqRgE7tt28/5lpo9KOPTi0i1,iv:JJc8MkmVNyoqklBU5gCzPNZ04DgenBPpbjLzAnMnHDg=,tag:IqkHLHfwLBsqzKlQnKs84Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:6UC6rt/A33pEKNnu434=,iv:SBvj/jTvT2DjzrDYOZ23RZ6Q3VA+gQ2vfUMJiQ11jvY=,tag:htTrc6W9RCNzPOxYVKzMlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1etvas2d04gjcylcld4j5asveqthhnrhy2uwmmjewsr728p2z3p4sqz7449
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdiszSlp6Z2JBZUF3aVpO
            VTIvQW5jNGIvUEZKL01MUHg0MzFsbG16bDJvCjQ1YjlQSEtaUFdsMnNGeGY2Vkt5
            WFZlTzAvUmQ0QkM2NlhuMFNJNlhkNWcKLS0tIEI0REtDdmdWTkl6QVlUbzJ2cW0z
            WGRVMTZLOHF6dHM4MDNtbHhCL3BRRGcK2gH0bDsZ1GBPZJrkfYoHRTsf8TdGUhl6
            KF1omjHmpY+3z2Ewmi4t0FiCJcDozVctguwlyKW5G8bKUtdEEDJbDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T05:21:59Z"
    mac: ENC[AES256_GCM,data:eWExk9ML3AOb6ahpwCttpgXhgby+TTG3BFEDCI1cfG6+CgTe7aMEbLgDKLDvxtxTN7LhjOACDFLNDWQnhAHR7CA3ffchlgCpjntzD9e7sBbKa8N01+UN0dm8BBusf9GNz5Ll1L2yytC6Q/mZLgNI+QdyIrxBbzlfBZqeJxezuVo=,iv:Q7ky15jotyd4na+1oe0iC+jsn1MXEgpRO8K18l1Op7s=,tag:HqNUVSdGhThWU9BHtPbYLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
