---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  COREDNS_ADDR: "10.45.0.10"
  KUBE_VIP_ADDR: "10.1.50.71"
  CLUSTER_CIDR: "10.44.0.0/16"
  SERVICE_CIDR: "10.45.0.0/16"
  NODE_CIDR: "10.1.50.0/24"
